services:
  database:
    image: postgres:alpine
    container_name: checkup_extension_db
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  backend:
    build: ./backend
    container_name: checkup_extension_backend
    ports:
      - "8081:8081"
    volumes:
      - problems-data:/app/utils/problems
    depends_on:
      database:
        condition: service_healthy

  web:
    image: nginx
    container_name: checkup_extension_static_sources
    ports:
      - "8082:8082"
    environment:
      - NGINX_PORT=8082
      - NGINX_SERVER_NAME=localhost
    volumes:
      - ./backend/nginx/templates:/etc/nginx/templates
      - problems-data:/var/www/screenshots:ro

  frontend:
    build: ./frontend
    container_name: checkup_extension_frontend
    ports:
      - "8080:8080"
    volumes:
      - problems-data:/app/public/snapshots
    depends_on:
      - backend

volumes:
  problems-data:
